"""
This script performs statistical similarity analysis between the real DASS dataset
and the generated synthetic data from CTGAN.
"""

import pandas as pd
import numpy as np
import os
import matplotlib.pyplot as plt
import seaborn as sns
from data_loader import MentalHealthDataLoader  # To load the real DASS data

# --- Configuration --- #
# WHY: These paths are configured to find the data and save the new reports
# in the correct locations within your project structure.
current_script_dir = os.path.dirname(os.path.abspath(__file__))
project_root = os.path.abspath(os.path.join(
    current_script_dir, "..", "..", ".."))

DATA_PATH = os.path.join(project_root, "data")  # Path to your raw data
LOG_DIR = os.path.join(project_root, "gan_logs") # Path where logs and data are saved

# *** MODIFICATION 1: Point to the new CTGAN synthetic data file. ***
SYNTHETIC_DATA_PATH = os.path.join(
    LOG_DIR, "ctgan_synthetic_data_for_validation.csv")

# *** MODIFICATION 2: Create new report and plot paths to avoid overwriting the baseline. ***
OUTPUT_REPORT_PATH = os.path.join(LOG_DIR, "ctgan_statistical_similarity_report.md")
OUTPUT_PLOTS_DIR = os.path.join(LOG_DIR, "ctgan_plots") # New directory for CTGAN plots

# Ensure output directory exists
os.makedirs(OUTPUT_PLOTS_DIR, exist_ok=True)

# --- Main Logic --- #
if __name__ == "__main__":
    print("\n--- Starting Statistical Similarity Analysis for CTGAN Data ---")

    # 1. Load Real DASS Data
    # WHY: We load the raw real data to serve as our ground truth for comparison.
    data_loader = MentalHealthDataLoader(DATA_PATH)
    real_dass_data = data_loader.load_dass_dataset()

    if real_dass_data is None:
        print("Error: Could not load real DASS dataset. Exiting.")
        exit()

    # Preprocess real data (but WITHOUT normalization)
    # WHY: CTGAN works with data in its original scale. To make a fair comparison,
    # we should compare the raw synthetic data to the raw real data.
    # We only select numerical columns and fill missing values.
    numerical_cols = real_dass_data.select_dtypes(include=np.number).columns
    real_processed_data = real_dass_data[numerical_cols].copy()
    real_processed_data = real_processed_data.fillna(real_processed_data.mean())

    print(f"Loaded and preprocessed real DASS data. Shape: {real_processed_data.shape}")

    # 2. Load Synthetic Data from CTGAN
    # WHY: We load the new synthetic data generated by the CTGAN model.
    try:
        synthetic_data = pd.read_csv(SYNTHETIC_DATA_PATH)
        print(f"Loaded CTGAN synthetic data. Shape: {synthetic_data.shape}")
    except FileNotFoundError:
        print(f"Error: Synthetic data file not found at {SYNTHETIC_DATA_PATH}. Please generate it first.")
        exit()
    
    # NOTE: The columns from CTGAN should already match the real data columns.

    # 3. Perform Statistical Comparisons
    # WHY: We generate a markdown report to systematically document the comparison.
    report_content = "# CTGAN Statistical Similarity Report\n\n"
    report_content += "This report compares the statistical properties of the real DASS dataset against the synthetic data generated by the CTGAN model.\n\n"
    report_content += "## Data Overview\n\n"
    report_content += f"- Real Data Shape: {real_processed_data.shape}\n"
    report_content += f"- Synthetic Data Shape: {synthetic_data.shape}\n\n"

    report_content += "## Mean and Standard Deviation Comparison\n\n"
    report_content += "### Real Data Statistics\n\n"
    report_content += real_processed_data.describe().to_markdown() + "\n\n"

    report_content += "### Synthetic Data Statistics\n\n"
    report_content += synthetic_data.describe().to_markdown() + "\n\n"

    # Compare means and std deviations for a few key columns
    report_content += "## Detailed Comparison of Key Features (Mean & Std Dev)\n\n"
    num_features_to_compare = min(10, real_processed_data.shape[1])
    for i in range(num_features_to_compare):
        col = real_processed_data.columns[i]
        real_mean = real_processed_data[col].mean()
        synth_mean = synthetic_data[col].mean()
        real_std = real_processed_data[col].std()
        synth_std = synthetic_data[col].std()
        report_content += f"- **{col}**\n"
        report_content += f"  - Real Mean: {real_mean:.4f}, Synthetic Mean: {synth_mean:.4f}\n"
        report_content += f"  - Real Std Dev: {real_std:.4f}, Synthetic Std Dev: {synth_std:.4f}\n"
    report_content += "\n"

    # 4. Visualize Distributions (Histograms for a few features)
    # WHY: Visual plots provide an intuitive understanding of how well the distributions match.
    report_content += "## Distribution Comparison (Histograms)\n\n"
    num_plots = min(5, real_processed_data.shape[1])
    for i in range(num_plots):
        col = real_processed_data.columns[i]
        plt.figure(figsize=(8, 5))
        sns.histplot(real_processed_data[col], color='blue', label='Real', kde=True, stat='density', alpha=0.5)
        sns.histplot(synthetic_data[col], color='red', label='Synthetic (CTGAN)', kde=True, stat='density', alpha=0.5)
        plt.title(f'Distribution of {col} (CTGAN vs Real)')
        plt.xlabel(col)
        plt.ylabel('Density')
        plt.legend()
        # Use the new plots directory
        plot_filename = os.path.join(OUTPUT_PLOTS_DIR, f'ctgan_distribution_{col}.png')
        plt.savefig(plot_filename)
        plt.close()
        # Use a relative path for markdown compatibility
        report_content += f"![Distribution of {col}]({os.path.relpath(plot_filename, LOG_DIR)})\n\n"

    # 5. Correlation Matrix Comparison
    # WHY: This helps us see if the GAN learned the relationships between features, not just individual distributions.
    report_content += "## Correlation Matrix Comparison\n\n"
    subset_cols = real_processed_data.columns[:min(20, real_processed_data.shape[1])]
    real_corr = real_processed_data[subset_cols].corr()
    synthetic_corr = synthetic_data[subset_cols].corr()

    plt.figure(figsize=(12, 6))
    plt.subplot(1, 2, 1)
    sns.heatmap(real_corr, cmap='coolwarm', annot=False)
    plt.title('Real Data Correlation')
    plt.subplot(1, 2, 2)
    sns.heatmap(synthetic_corr, cmap='coolwarm', annot=False)
    plt.title('Synthetic Data Correlation (CTGAN)')
    plt.tight_layout()
    # Use the new plots directory
    corr_plot_filename = os.path.join(OUTPUT_PLOTS_DIR, 'ctgan_correlation_matrices.png')
    plt.savefig(corr_plot_filename)
    plt.close()
    report_content += f"![Correlation Matrices]({os.path.relpath(corr_plot_filename, LOG_DIR)})\n\n"

    # Save the report
    with open(OUTPUT_REPORT_PATH, "w") as f:
        f.write(report_content)
    print(f"Statistical similarity report saved to: {OUTPUT_REPORT_PATH}")
    print(f"Plots saved to: {OUTPUT_PLOTS_DIR}")
    print("Statistical similarity analysis for CTGAN complete.")
